application: polar-program-97805
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# メニュー
- url: /sakura000/.*
  script: sakura000.app

# 家賃共益費一覧
- url: /sakura010/.*
  script: sakura010.app

# 家賃共益費入力
- url: /sakura015/.*
  script: sakura015.app

# 電気代一覧
- url: /sakura020/.*
  script: sakura020.app

# 電気代入力
- url: /sakura025/.*
  script: sakura025.app

# 領収書印刷
- url: /sakura100/.*
  script: sakura100.app

# 家賃共益一覧印刷
- url: /sakura110/.*
  script: sakura110.app
# 電気代一覧印刷
- url: /sakura115/.*
  script: sakura115.app
# 電気代一覧印刷(経理部用）
- url: /sakura116/.*
  script: sakura116.app

# 出金伝票印刷
- url: /sakura120/.*
  script: sakura120.app

# 家賃・共益・電気代マスタ
- url: /sakura900/.*
  script: sakura900.app
- url: /sakura905/.*
  script: sakura905.app

# 患者マスタ
- url: /sakura910/.*
  script: sakura910.app
- url: /sakura915/.*
  script: sakura915.app

# 居室マスタ
- url: /sakura920/.*
  script: sakura920.app
- url: /sakura925/.*
  script: sakura925.app

# 項目マスタ
- url: /sakura930/.*
  script: sakura930.app
- url: /sakura935/.*
  script: sakura935.app

- url: .*
  script: sakura000.app

libraries:
- name: webapp2
  version: "2.5.2"
